### PR TITLE
questid2display update

### PR DESCRIPTION
**Pull request by Ridley8819**
Phantasmagorika
Verus City
Horror Toy Factory
Charston Factory
RWC 2012
Started the new 2015 Beginners Quest

### CODE REVIEW

**Comment by dastgir** [comment]
Completed? Or it is still WIP PR?

**Comment by Ridley8819** [comment]
everything except the 2015 beginners quest (21001) is completed. but i won't continue them atm. I just added it so i don't forget the ID :)

**Comment by dastgir** [comment]
Thank you

**Comment by cydh** [comment]
U're welcome xD

**Pull request merged**
