### PR TITLE
Use better message translation while casting a skill to target.

### PR DESCRIPTION
**Pull request by exneval**
Signed-off-by: exneval <exneval.rayz@gmail.com>

### CODE REVIEW

**Comment by zackdreaver** [comment]
i don't get it, when you said "broken" official translation is "better" translation
this line was mean for kRO and jRO server, not for english server, that's why this kinda silly when translated to english
.. just saying

it's been decided after this issue
https://github.com/ROClientSide/Translation/issues/34

**Comment by dastgir** [comment]
That's not better.

With iro its " To [exneval] use [Fire Bolt] skill"
With current its "[exneval] use [Fire Bolt] skill"

**Comment by exneval** [comment]
Well..
You can test this ingame..

With current translation..
The target who casted the skill..

While with iRO trans..
We cast skill to the target

**Comment by zackdreaver** [comment]
that's why i said it's silly when translated to english,
I prefer 1 fixed translation than 2 broken translations

**Comment by exneval** [comment]
What's in iRO is better I guess..

With current trans..
While casting Ashura to enemy
It will say, Enemy use Ashura skill

While it should be..
To Enemy use Ashura skill

**Comment by zackdreaver** [comment]
Give us better translation than iRO did
i don't want engrish translation

**Comment by dastgir** [comment]
iRO translation sounds incomplete, any other better sentence formation will be accepted.

**Comment by exneval** [comment]
Well, iRO just make it short and clear .

The complete sentence would be..
1. Cast to [Target] by using [Ashura Strike] skill.
2. Cast skill to [Target] by using [Ashura Strike]

**Comment by dastgir** [comment]
@exneval
Can you squash the commit into 1?

**Comment by exneval** [comment]
I'm new to Git,
Still googling how to squash...  LOL

**Comment by dastgir** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by exneval** [comment]
aw..  I messed up.. Help ...

**Comment by dastgir** [comment]
Merged

**Pull request merged**
