### PR TITLE
Add Rebellion skills animation.

### PR DESCRIPTION
**Pull request by exneval**
Signed-off-by: exneval <exneval.rayz@gmail.com>

### CODE REVIEW

**Comment by zackdreaver** [comment]
Have you test it?
AFAIK this file never used on newer client that use folder luafiles514
i don't get it at first why this files exist in this folder.

**Comment by exneval** [comment]
yep.. tested in rA

in luafiles514/lua files/skilleffectinfolist.lub
the EF_* ID was declared..

but not define in luafiles514/lua files/effectid.lub

ex:
[SKID.RL_D_TAIL] = {
		targetWaveFileName = "effect\\RL_D_TAIL.wav",
		targetEffectNum = 1,
		targetEffectID = { EFID.EF_D_TAIL }
	},

**Comment by dastgir** [comment]
@zackdreaver 
kRO have these lines, so we should too have them.

@exneval 
Thanks for Contribution. :+1:

**Comment by exneval** [comment]
@dastgir 
You're welcome....

**Pull request merged**
